update cloudbuild

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -101,6 +101,8 @@ steps:
                   "$$BUILD_ID" \
               )" \
             "https://api.github.com/repos/$REPO_FULL_NAME/issues/$_PR_NUMBER/comments"
+            # Ensure the build fails here if the docker build fails in the step above
+            exit 1
           fi
   # Run the container and execute the bazel test run command
   - name: 'gcr.io/cloud-builders/docker'
@@ -114,7 +116,7 @@ steps:
           bazel run //:python_tests &&
         if [ "$$GLIBC_TAR_CACHE" != "true" ]; then
           echo "Copying current glibc build"
-          docker cp lind_test_container:/home/lind/lind-wasm/src/glibc/build /workspace/glibcbuild
+          docker cp lind_test_container:/home/lind/lind-wasm/src/glibc/build /workspace/build
         fi
         docker cp lind_test_container:/home/lind/lind-wasm/src/RawPOSIX/tmp/results.json /workspace/results.json &&
         docker cp lind_test_container:/home/lind/lind-wasm/src/RawPOSIX/tmp/report.html /workspace/report.html &&
@@ -142,7 +144,7 @@ steps:
         source /workspace/env.txt
         if [ "$$GLIBC_TAR_CACHE" != "true" ]; then
           echo "creating tar ball"
-          tar czf /workspace/glibc_build.tar.gz -C /workspace/glibcbuild
+          tar czf /workspace/glibc_build.tar.gz -C /workspace build
           echo "pushing tar to gcs"
           gsutil cp /workspace/glibc_build.tar.gz gs://test_result_json_bucket/glibc/$$LAST_COMMIT/glibc_build.tar.gz 
         fi      
